### ISSUE TITLE
[BUG?] Implementation of daisy-chained serial devices

### ISSUE THREAD

**Issue by kadykov** [yaq-project/yaq-fyi#79]
Thank you for this fantastic project.

I'm trying to implement a `yaq` daemon for daisy-chained XY motorized stages, and I cannot figure out how to do it.

I made a `yaq` daemon and tested it with one axis, and everything works great. 
But when I add the second axis to the configuration file, the second daemon crashes, while the first one continues to work.
When I change the configuration file such as each daemon has its own serial port, then both daemons work great.

It seems like a bug to me, but maybe I just don't understand how daisy-chaining should be implemented in `yaq`.

Thank you in advance for your help.

<details> 
<summary>Some details</summary>

When the daemon configuration is like that, everything works great:
```toml
[stage_x]

port = 39003
serial_port = "COM8"
baud_rate = 38400
address = 0
log_level = "debug"
log_to_file = "True"
```

But when I try to add the second axis like this, the second daemon crashes, but the first one works:
```toml
[stage_x]

port = 39003
serial_port = "COM8"
baud_rate = 38400
address = 0
log_level = "debug"
log_to_file = "True"

[stage_y]

port = 39004
serial_port = "COM8"
baud_rate = 38400
address = 1
log_level = "debug"
log_to_file = "True"
```

The console daemon output is like that:
```sh
(test) C:\Users\username\Documents\prog\project_name\serial>yaqd-DaemonName
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : Config File Path = C:\Users\username\AppData\Local\yaq\yaqd\DaemonName\config.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : State File Path = C:\Users\username\AppData\Local\yaq\yaqd-state\DaemonName\stage_x-state.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : TCP Port = 39003
<6> INFO : 2023-08-18T17:22:31+0200 : stage_y : Config File Path = C:\Users\username\AppData\Local\yaq\yaqd\DaemonName\config.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_y : State File Path = C:\Users\username\AppData\Local\yaq\yaqd-state\DaemonName\stage_y-state.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_y : TCP Port = 39004
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<IsDaemon._main() done, defined at C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py:210> exception=UnboundLocalError("cannot access local variable 'daemon' where it is not associated with a value")>
Traceback (most recent call last):
  File "C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py", line 224, in _main
    await cls._start_daemon(section, config, config_filepath)
  File "C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py", line 252, in _start_daemon
    server(daemon), config.get("host", ""), config.get("port", None)
           ^^^^^^
UnboundLocalError: cannot access local variable 'daemon' where it is not associated with a value
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\username\mambaforge\envs\test\Lib\asyncio\windows_events.py:600> wait_for=<_OverlappedFuture cancelled>>
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\username\mambaforge\envs\test\Lib\asyncio\windows_events.py:600> wait_for=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\mambaforge\envs\test\Scripts\yaqd-DaemonName.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py", line 204, in main
    loop.run_forever()
  File "C:\Users\username\mambaforge\envs\test\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\username\mambaforge\envs\test\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\username\mambaforge\envs\test\Lib\asyncio\base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\test\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
  File "C:\Users\username\mambaforge\envs\test\Lib\asyncio\windows_events.py", line 817, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<IsDaemon.save_state() done, defined at C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py:342> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<DaemonName.update_state() done, defined at C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_mercury\_DaemonName.py:71> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-45' coro=<Event.wait() done, defined at C:\Users\username\mambaforge\envs\test\Lib\asyncio\locks.py:200> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[_release_waiter(<Future pendi...ask_wakeup()]>)() at C:\Users\username\mambaforge\envs\test\Lib\asyncio\tasks.py:421]>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<DaemonName.update_state() running at C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_mercury\_DaemonName.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IsDaemon.save_state() running at C:\Users\username\mambaforge\envs\test\Lib\site-packages\yaqd_core\_is_daemon.py:354> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<Server.serve_forever() running at C:\Users\username\mambaforge\envs\test\Lib\asyncio\base_events.py:369> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-44' coro=<Event.wait() running at C:\Users\username\mambaforge\envs\test\Lib\asyncio\locks.py:213> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[_release_waiter(<Future pendi...ask_wakeup()]>)() at C:\Users\username\mambaforge\envs\test\Lib\asyncio\tasks.py:421]>
^C
```

Unfortunately, there is not much in the both log files:
```log
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : Config File Path = C:\Users\username\AppData\Local\yaq\yaqd\DaemonName\config.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : State File Path = C:\Users\username\AppData\Local\yaq\yaqd-state\DaemonName\stage_x-state.toml
<6> INFO : 2023-08-18T17:22:31+0200 : stage_x : TCP Port = 39003
```

There is no problem when each daemon has its own serial port like this:
```toml
[stage_x]

port = 39003
serial_port = "COM8"
baud_rate = 38400
address = 0
log_level = "debug"
log_to_file = "True"

[stage_y]

port = 39004
serial_port = "COM5"
baud_rate = 38400
address = 1
log_level = "debug"
log_to_file = "True"
```

The main daemon class is like this:
```python
import asyncio
from dataclasses import dataclass, field
from typing import Any, Dict, List

import serial
from yaqd_core import HasLimits, HasPosition, IsDaemon, UsesSerial, UsesUart, aserial

class DaemonName(UsesUart, UsesSerial, HasLimits, HasPosition, IsDaemon):
    _kind = "DaemonName"

    def __init__(self, name, config, config_filepath):
        super().__init__(name, config, config_filepath)
        # Perform any unique initialization
        # self._ser = serial.Serial(
        self._ser = aserial.ASerial(
            self._config["serial_port"],
            baudrate=self._config["baud_rate"],
            # eol="\r\n\x03".encode(),
        )

    async def update_state(self):
        """Continually monitor and update the current daemon state."""
        # If there is no state to monitor continuously, delete this function
        while True:
            # Perform any updates to internal state
            self._busy = False
            # There must be at least one `await` in this loop
            # This one waits for something to trigger the "busy" state
            # (Setting `self._busy = True)
            # Otherwise, you can simply `await asyncio.sleep(0.01)`
            await self._busy_sig.wait()

    def _set_position(self, position: float) -> None:
        self._loop.create_task(self._aset_position(position))

    def direct_serial_write(self, message: bytes):
        self._ser.write(message)
```

Tested version:
```sh
# Name                    Version                   Build  Channel
yaqc                      2023.6.0           pyhd8ed1ab_0    conda-forge
yaqd-control              2022.4.0           pyhd8ed1ab_0    conda-forge
yaqd-core                 2023.6.0                 pypi_0    pypi
```
</details>

**Comment by untzag** [comment]
Hi @kadykov!

I don't have time to look closely at your work at the moment, but just reading your summary my first thought is that serial objects are blocking. You can't create two serial interfaces at the same time.

This is a common challenge in daemon development, and we tend to get around this problem using class attributes like this.

**Comment by kadykov** [comment]
Thank you @untzag!
Should this code be in the `aserial` module [like this](https://github.com/yaq-project/yaq-python/pull/67#issue-1859085476)?
